-- CONTROL INTERVAL 1
WCONPROD
--      WELL     OPEN/  CNTL   OIL  WATER   GAS  LIQU   RES   BHP
--      NAME     SHUT   MODE  RATE   RATE  RATE  RATE  RATE
        'p1'    'OPEN'  'BHP'   5*                            180.08/
        'p2'    'OPEN'  'BHP'   5*                            180.019/
        'p3'    'OPEN'  'ORAT'  5  5*    /
        'p4'    'OPEN'  'BHP'   5*                            180.256/
        'p5'    'OPEN'  'ORAT'  5  5*    /
/ 

WCONINJE
--      WELL     INJ   OPEN/   CNTL    FLOW   RES    BHP
--      NAME    TYPE   SHUT    MODE    RATE   RATE  TARGET
        'i1'   'WATER' 'OPEN' 'RATE'   300/
        'i2'   'WATER' 'OPEN' 'RATE'   152.222/
/

TSTEP
1 2 4 8 16 32 50 50 50 50 50 50 50 50 50 34.5 
/

-- CONTROL INTERVAL 2
WCONPROD
--      WELL     OPEN/  CNTL   OIL  WATER   GAS  LIQU   RES   BHP
--      NAME     SHUT   MODE  RATE   RATE  RATE  RATE  RATE
        'p1'    'OPEN'  'BHP'   5*                            182.332/
        'p2'    'OPEN'  'BHP'   5*                            181.283/
        'p3'    'OPEN'  'ORAT'  5  5*    /
        'p4'    'OPEN'  'BHP'   5*                            183.6/
        'p5'    'OPEN'  'ORAT'  5  5*    /
/ 

WCONINJE
--      WELL     INJ   OPEN/   CNTL    FLOW   RES    BHP
--      NAME    TYPE   SHUT    MODE    RATE   RATE  TARGET
        'i1'   'WATER' 'OPEN' 'RATE'   252.736/
        'i2'   'WATER' 'OPEN' 'RATE'   100/
/

TSTEP
1 2 4 8 16 32 50 50 50 50 50 50 50 50 50 34.5 
/

-- CONTROL INTERVAL 3
WCONPROD
--      WELL     OPEN/  CNTL   OIL  WATER   GAS  LIQU   RES   BHP
--      NAME     SHUT   MODE  RATE   RATE  RATE  RATE  RATE
        'p1'    'OPEN'  'BHP'   5*                            185.718/
        'p2'    'OPEN'  'BHP'   5*                            189.806/
        'p3'    'OPEN'  'ORAT'  5  5*    /
        'p4'    'OPEN'  'BHP'   5*                            185.611/
        'p5'    'OPEN'  'ORAT'  5  5*    /
/ 

WCONINJE
--      WELL     INJ   OPEN/   CNTL    FLOW   RES    BHP
--      NAME    TYPE   SHUT    MODE    RATE   RATE  TARGET
        'i1'   'WATER' 'OPEN' 'RATE'   300/
        'i2'   'WATER' 'OPEN' 'RATE'   73.7928/
/

TSTEP
1 2 4 8 16 32 50 50 50 50 50 50 50 50 50 34.5 
/

-- CONTROL INTERVAL 4
WCONPROD
--      WELL     OPEN/  CNTL   OIL  WATER   GAS  LIQU   RES   BHP
--      NAME     SHUT   MODE  RATE   RATE  RATE  RATE  RATE
        'p1'    'OPEN'  'BHP'   5*                            186.489/
        'p2'    'OPEN'  'BHP'   5*                            180/
        'p3'    'OPEN'  'ORAT'  5  5*    /
        'p4'    'OPEN'  'BHP'   5*                            182.09/
        'p5'    'OPEN'  'ORAT'  5  5*    /
/ 

WCONINJE
--      WELL     INJ   OPEN/   CNTL    FLOW   RES    BHP
--      NAME    TYPE   SHUT    MODE    RATE   RATE  TARGET
        'i1'   'WATER' 'OPEN' 'RATE'   237.045/
        'i2'   'WATER' 'OPEN' 'RATE'   100.3054/
/

TSTEP
1 2 4 8 16 32 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 49.5 
/

-- CONTROL INTERVAL 5
WCONPROD
--      WELL     OPEN/  CNTL   OIL  WATER   GAS  LIQU   RES   BHP
--      NAME     SHUT   MODE  RATE   RATE  RATE  RATE  RATE
        'p1'    'OPEN'  'BHP'   5*                            186.352/
        'p2'    'OPEN'  'BHP'   5*                            180/
        'p3'    'OPEN'  'ORAT'  5  5*    /
        'p4'    'OPEN'  'BHP'   5*                            182.53/
        'p5'    'OPEN'  'ORAT'  5  5*    /
/ 

WCONINJE
--      WELL     INJ   OPEN/   CNTL    FLOW   RES    BHP
--      NAME    TYPE   SHUT    MODE    RATE   RATE  TARGET
        'i1'   'WATER' 'OPEN' 'RATE'   138.37/
        'i2'   'WATER' 'OPEN' 'RATE'   86.2628/
/

TSTEP
1 2 4 8 16 32 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 32 
/

