function [ v ] = vectorTimesZ(vx,vu,vv,Ax,Av,ci)


if ~isempty(Av)
    v = cellfun(@(xi,vi,ui)xi+vi+ui, ...
        cellmtimesT( vx,Ax,'lowerTriangular',true,'ci',ci,'columnVector',false),...
        cellmtimesT( vv,Av,'lowerTriangular',true,'ci',ci,'columnVector',false),...
        vu,...
        'UniformOutput',false);
else
    v = cellfun(@(xi,ui)xi+ui, ...
        cellmtimesT( vx,Ax,'lowerTriangular',true,'ci',ci,'columnVector',false),...
        vu,...
        'UniformOutput',false);
end


end

