function [firstOrderOpt] = testFirstOrderOpt(M,objPartials,duN,dxN,dvN,mu,withAlgs)
%%% evaluates to approx 0 if QP is correctly solved

duV = cell2mat(duN);

firstOrderOpt = duV' * M * duV + sum([...
    sum(cellfun(@(Jz,dz)Jz*dz,objPartials.Jx',dxN));...
    sum(cellfun(@(Jz,dz)Jz*dz,objPartials.Ju',duN));...
    sum(cellfun(@(dz,uz,lz)((uz-lz)'*dz),dxN,mu.ub.x,mu.lb.x));...
    sum(cellfun(@(dz,uz,lz)((uz-lz)'*dz),duN,mu.ub.u,mu.lb.u))...
    ]);
if withAlgs
    firstOrderOpt = firstOrderOpt + sum([sum(cellfun(@(Jz,dz)Jz*dz,objPartials.Jv',dvN));...
        sum(cellfun(@(dz,uz,lz)((uz-lz)'*dz),dvN,mu.ub.v,mu.lb.v))...
        ]);
end


end
